server.port: 37090
spring.application:
  name: hjy-api-gw


spring.config.import: api-gw.yml,eureka-client.yml


spring.zipkin:
  base-url: http://localhost:9411

spring.sleuth.sampler.probability: 1.0


